[package]
name = "vision-2020"
version = "0.1.0"
authors = []
edition = "2018"
default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[features]
opencl = []

[dependencies]
opencv = { version = "0.29", default-features = false, features = ["opencv-4"] }
stdvis-core = { git = "https://github.com/RoboticsTeam4904/standard-vision" }
stdvis-opencv = { git = "https://github.com/RoboticsTeam4904/standard-vision" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray = "0.13"
anyhow = "1.0"

[target.'cfg(linux)'.dependencies]
opencv = { version = "0.30", default-features = false, features = ["opencv-4", "contrib"] }

[target.'cfg(not(linux))'.dependencies]
opencv = { version = "0.30", default-features = false, features = ["opencv-4", "contrib", "buildtime-bindgen"] }
