[package]
name = "vision-2020"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
opencv = { version = "0.29", default-features = false, features = ["opencv-4"] }
stdvis-core = { path = "../standard-vision/stdvis-core" }
stdvis-opencv = { path = "../standard-vision/stdvis-opencv" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
